# Generated by Django 2.1.3 on 2019-07-04 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CmdrModel',
            new_name='Cmdr',
        ),
    ]
