# Generated by Django 2.2.5 on 2019-09-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('stock_price', models.CharField(max_length=100)),
                ('stock_gain', models.CharField(max_length=100)),
                ('market_name', models.CharField(max_length=200)),
            ],
        ),
    ]
