# Generated by Django 3.0.2 on 2020-01-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.IntegerField(unique=True),
        ),
    ]
